version: "3.7"

services:
  mydjango:
    build: ./mydjangoproject/
    command: python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mydjangoproject/:/usr/app
    ports:
      - 8000:8000


  